[workspace]
resolver = "2"
members = ["crates/core", "crates/py"]

[workspace.package]
version = "0.1.1"
edition = "2021"
rust-version = "1.83"
license = "LGPL-2.1-only"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "unwind" # panics are caught at the FFI boundary and mapped to Python exceptions
debug = false
strip = "symbols"
